### ISSUE TITLE
Requires middleware to add handlers.

### ISSUE THREAD

**Issue by ianlewis** [zain/jogging#1]
jogging shouldn't require you to add the LoggingMiddleware in order to register the logging handlers. It should only require you to put 'jogging' in INSTALLED_APPS. Adding the logging handlers should happen in **init**.py or models.py

**Comment by unbracketed** [comment]
I'd also like to see an alternative approach to having the handlers registered. Logging won't work when unit tests are being run since the middleware never gets invoked.

**Comment by danaspiegel** [comment]
or in management commands...

**Comment by ianlewis** [comment]
Management commands wouldn't work. The python logging module needs to be initialized in the running process.

I've implemented the fix for this in my branch but Zain didn't want to import it for some reason.

**Comment by ianlewis** [comment]
Unbracketed. That's one of the reasons I submitted the bug.

**Comment by danaspiegel** [comment]
I forked and fixed this as well as a few other items: http://github.com/cathedralpartners/jogging/

Please feel free to pull from our fork.

**Comment by ianlewis** [comment]
I see what you meant my management commands. Kindly disregard my earlier comment ;p

**Comment by zain** [comment]
I pulled IanLewis's branch, which fixes this and also includes danaspiegel's fixes. Thanks guys.
