### ISSUE TITLE
Does jogging work with Python 2.4?

### ISSUE THREAD

**Issue by stodge** [zain/jogging#11]
I don't have a spare machine to test this yet, but does jogging work on Python 2.4?

**Comment by zain** [comment]
No, it doesn't. There's an old branch that supports py2.4 which you can use, but it's missing some bugfixes and features. Theoretically it shouldn't be hard to make master work with py2.4; AFAIK, only one change should be required, which is detailed in commit c3b476c4005176d2edf1e37003b595a19c7126f8.
