### ISSUE TITLE
Mixing GLOBAL_LOG_HANDLERS and LOGGING dict doesn't seem to work right

### ISSUE THREAD

**Issue by sadohert** [zain/jogging#5]
Hi, I have a configuration where I want the global logger to be defined in settings.py, as well as module specific handlers using the LOGGING variable.  This _could_ have something to do with me using python 2.4, but I'm not sure how (more about that later).  I _think_ line 71 on:

jogging / jogging / models.py

could maybe be switched to an "if", instead of "elif".  So that even if settings.py contains a "LOGGING" variable, if it happens to contain the GLOBAL variables as well then they will get setup too.  I was seeing the "root" logger not setup with a handler, and so I wasn't getting some logs.

Also, in **init**.py (around 71 oddly enough) I was having a problem with keyword argument being added to kwarg and passed to the python logger.  It complained about the unknown variable "source".  Not sure if this is an issue with verison 2.4 of the python logger, but according to the docs online I don't see why it would be a problem.  Anywho... I don't append the 'source' argument now, which is unfortunate, but it allowed me to move forward.

**Comment by zain** [comment]
Regarding the second part of the issue (unknown variable "source"), that is indeed an issue with python 2.4. The workaround is to get rid of the "source" variable from the call.

This workaround is a part of the py2.4 branch (this branch is functional, but is lagging behind the master branch feature-wise) here: http://github.com/zain/jogging/commit/c3b476c4005176d2edf1e37003b595a19c7126f8

**Comment by zmt** [comment]
I had the same question on the first part a long time ago. I might just fix that myself (because I really want to). I like the idea of a default GLOBAL and customizable underneath coexisting in harmony.

**Comment by ianlewis** [comment]
Fixed issue with Global logging handlers not getting set if the user has set the LOGGING setting. Fixed tests a bit. Closed by cbc2721dc4621351515e5dc0aea2e322507c8da9
