### ISSUE TITLE
os.uname() is not avaliable in Windows.

### ISSUE THREAD

**Issue by canassa** [zain/jogging#6]
The module is crashing if you try to run it windows:

  File "C:\Users\Cesar\Documents\Projetos\RM2\mysite\local_settings.py", line 3, in <module>
    from jogging.handlers import DatabaseHandler
  File "C:\Python26\lib\site-packages\jogging\handlers.py", line 4, in <module>
    HOST = os.uname()[1]
AttributeError: 'module' object has no attribute 'uname'

A easy fix for this is to use platform.uname() instead of os.uname()

**Comment by rwhitman** [comment]
I encountered the same issue on a Windows environment and can confirm that a platform.uname() patch works.

**Comment by ianlewis** [comment]
Updated the handlers module to get the host name from the platform module rather than the os module. Closed by 98033e4392a850df88419d4dbdf6e430e1211516

**Comment by Torkn** [comment]
socket.gethostname() would be a better choice than either platform.uname()[1] or os.uname()[1], unless you really want all the other information returned by platform.uname()

socket.getfqdn() is also available, returning the fully qualified hostname, but I'm not sure that is an advantage in this context.
